# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180206_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
