# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180206_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ing',
            field=models.ManyToManyField(to='myapp.Ingredient'),
        ),
    ]
