# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180206_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ing',
        ),
    ]
