# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_recipe_ing'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipes',
            field=models.ManyToManyField(default='', to='myapp.Recipe'),
        ),
    ]
