# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180206_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
