# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20180206_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='name',
        ),
        migrations.AddField(
            model_name='description',
            name='desc',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
