# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20180207_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='desc',
            new_name='name',
        ),
    ]
