# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20180207_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Recipe'),
        ),
    ]
