# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20180210_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
