# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_merge_20180210_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
